### ISSUE TITLE
Move to Java 17 as a baseline requirement

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-common#348]
It's time. (Is it time?)

**Comment by radcortez** [comment]
It is, and we discussed this a few times already.

One of the reasons we haven't moved yet was because Wildfly / EAP was still requiring 11 releases. @darranl what is the current state?

**Comment by jponge** [comment]
It's on the card for Mutiny: https://github.com/smallrye/smallrye-mutiny/issues/1444
