### ISSUE TITLE
Introduce a way to get "child" elements of the `Resource` abstraction

### ISSUE THREAD

**Issue by geoand** [smallrye/smallrye-common#359]
I encountered a case where I need to replace something that contains `Path` with something that will use `Resource`but I really need to know to be able to get the contents of the directory - if it is one.

**Comment by dmlloyd** [comment]
The methods `Resource#isDirectory()`/`Resource#openDirectoryStream()` should work for this use case. Could you try it?

**Comment by geoand** [comment]
That does the trick, thanks!
