### ISSUE TITLE
Provide basic NIO-based PathUtils

### ISSUE THREAD

**Issue by boris-unckel** [smallrye/smallrye-common#98]
Current IO utility libraries suffer from their early birth and a based on a java.io and java.nio mix. 
The approach is to have the file management methods of [java.nio.file.Files](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html) with [io.smallrye.common.constraint.Assert](https://github.com/smallrye/smallrye-common/blob/main/constraint/src/main/java/io/smallrye/common/constraint/Assert.java) null checks and [java.nio.file.Paths](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html) parameters. The same methods shall be available for classic java.io.File with underlying NIO to ease legacy use. All methods shall follow a fluent style and throw java.io.UncheckedIOException in error cases.

- distinct between "exception shows result" (i.E. NotLinkException) and "exception shows error in determination" (i.E. NoSuchFileException)
- utilizing SafeDirectoryStreams (providing native filesystem support in NIO) for recursive directory deletion
- avoid NIO pitfall when deleting dead symbolic links

**Comment by dmlloyd** [comment]
This PR was withdrawn a while ago. Reopen if needed.
